# Generated by Django 4.0.2 on 2022-08-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
